/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppDashboardRouteRouteImport } from './routes/_app/dashboard/route'
import { Route as AppDashboardResourcesRouteImport } from './routes/_app/dashboard/resources'
import { Route as AppDashboardHomeRouteImport } from './routes/_app/dashboard/home'
import { Route as AppDashboardEnrolledRouteImport } from './routes/_app/dashboard/enrolled'
import { Route as AppPaymentCourseIdRouteRouteImport } from './routes/_app/payment/$courseId/route'
import { Route as AppCoursesSlugRouteRouteImport } from './routes/_app/courses/$slug/route'
import { Route as AppDashboardCoursesIndexRouteImport } from './routes/_app/dashboard/courses/index'
import { Route as AppPaymentCourseIdPayRouteImport } from './routes/_app/payment/$courseId/pay'
import { Route as AppPaymentCourseIdCallbackRouteImport } from './routes/_app/payment/$courseId/callback'
import { Route as AppPaymentCourseIdSplatRouteImport } from './routes/_app/payment/$courseId/$'
import { Route as AppDashboardCoursesNewRouteImport } from './routes/_app/dashboard/courses/new'
import { Route as AppCoursesSlugIntroductionRouteImport } from './routes/_app/courses/$slug/introduction'
import { Route as AppCoursesSlugWeekRouteImport } from './routes/_app/courses/$slug/$week'
import { Route as AppDashboardCoursesSlugEditRouteImport } from './routes/_app/dashboard/courses/$slug/edit'
import { ServerRoute as ApiInfoServerRouteImport } from './routes/api/info'

const rootServerRouteImport = createServerRootRoute()

const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppDashboardRouteRoute = AppDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardResourcesRoute = AppDashboardResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppDashboardRouteRoute,
} as any)
const AppDashboardHomeRoute = AppDashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppDashboardRouteRoute,
} as any)
const AppDashboardEnrolledRoute = AppDashboardEnrolledRouteImport.update({
  id: '/enrolled',
  path: '/enrolled',
  getParentRoute: () => AppDashboardRouteRoute,
} as any)
const AppPaymentCourseIdRouteRoute = AppPaymentCourseIdRouteRouteImport.update({
  id: '/payment/$courseId',
  path: '/payment/$courseId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoursesSlugRouteRoute = AppCoursesSlugRouteRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardCoursesIndexRoute =
  AppDashboardCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AppDashboardRouteRoute,
  } as any)
const AppPaymentCourseIdPayRoute = AppPaymentCourseIdPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => AppPaymentCourseIdRouteRoute,
} as any)
const AppPaymentCourseIdCallbackRoute =
  AppPaymentCourseIdCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => AppPaymentCourseIdRouteRoute,
  } as any)
const AppPaymentCourseIdSplatRoute = AppPaymentCourseIdSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppPaymentCourseIdRouteRoute,
} as any)
const AppDashboardCoursesNewRoute = AppDashboardCoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => AppDashboardRouteRoute,
} as any)
const AppCoursesSlugIntroductionRoute =
  AppCoursesSlugIntroductionRouteImport.update({
    id: '/introduction',
    path: '/introduction',
    getParentRoute: () => AppCoursesSlugRouteRoute,
  } as any)
const AppCoursesSlugWeekRoute = AppCoursesSlugWeekRouteImport.update({
  id: '/$week',
  path: '/$week',
  getParentRoute: () => AppCoursesSlugRouteRoute,
} as any)
const AppDashboardCoursesSlugEditRoute =
  AppDashboardCoursesSlugEditRouteImport.update({
    id: '/courses/$slug/edit',
    path: '/courses/$slug/edit',
    getParentRoute: () => AppDashboardRouteRoute,
  } as any)
const ApiInfoServerRoute = ApiInfoServerRouteImport.update({
  id: '/api/info',
  path: '/api/info',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/dashboard': typeof AppDashboardRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/courses/$slug': typeof AppCoursesSlugRouteRouteWithChildren
  '/payment/$courseId': typeof AppPaymentCourseIdRouteRouteWithChildren
  '/dashboard/enrolled': typeof AppDashboardEnrolledRoute
  '/dashboard/home': typeof AppDashboardHomeRoute
  '/dashboard/resources': typeof AppDashboardResourcesRoute
  '/courses/$slug/$week': typeof AppCoursesSlugWeekRoute
  '/courses/$slug/introduction': typeof AppCoursesSlugIntroductionRoute
  '/dashboard/courses/new': typeof AppDashboardCoursesNewRoute
  '/payment/$courseId/$': typeof AppPaymentCourseIdSplatRoute
  '/payment/$courseId/callback': typeof AppPaymentCourseIdCallbackRoute
  '/payment/$courseId/pay': typeof AppPaymentCourseIdPayRoute
  '/dashboard/courses': typeof AppDashboardCoursesIndexRoute
  '/dashboard/courses/$slug/edit': typeof AppDashboardCoursesSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/dashboard': typeof AppDashboardRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/courses/$slug': typeof AppCoursesSlugRouteRouteWithChildren
  '/payment/$courseId': typeof AppPaymentCourseIdRouteRouteWithChildren
  '/dashboard/enrolled': typeof AppDashboardEnrolledRoute
  '/dashboard/home': typeof AppDashboardHomeRoute
  '/dashboard/resources': typeof AppDashboardResourcesRoute
  '/courses/$slug/$week': typeof AppCoursesSlugWeekRoute
  '/courses/$slug/introduction': typeof AppCoursesSlugIntroductionRoute
  '/dashboard/courses/new': typeof AppDashboardCoursesNewRoute
  '/payment/$courseId/$': typeof AppPaymentCourseIdSplatRoute
  '/payment/$courseId/callback': typeof AppPaymentCourseIdCallbackRoute
  '/payment/$courseId/pay': typeof AppPaymentCourseIdPayRoute
  '/dashboard/courses': typeof AppDashboardCoursesIndexRoute
  '/dashboard/courses/$slug/edit': typeof AppDashboardCoursesSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/assessment': typeof AssessmentRoute
  '/_app/dashboard': typeof AppDashboardRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/courses/$slug': typeof AppCoursesSlugRouteRouteWithChildren
  '/_app/payment/$courseId': typeof AppPaymentCourseIdRouteRouteWithChildren
  '/_app/dashboard/enrolled': typeof AppDashboardEnrolledRoute
  '/_app/dashboard/home': typeof AppDashboardHomeRoute
  '/_app/dashboard/resources': typeof AppDashboardResourcesRoute
  '/_app/courses/$slug/$week': typeof AppCoursesSlugWeekRoute
  '/_app/courses/$slug/introduction': typeof AppCoursesSlugIntroductionRoute
  '/_app/dashboard/courses/new': typeof AppDashboardCoursesNewRoute
  '/_app/payment/$courseId/$': typeof AppPaymentCourseIdSplatRoute
  '/_app/payment/$courseId/callback': typeof AppPaymentCourseIdCallbackRoute
  '/_app/payment/$courseId/pay': typeof AppPaymentCourseIdPayRoute
  '/_app/dashboard/courses/': typeof AppDashboardCoursesIndexRoute
  '/_app/dashboard/courses/$slug/edit': typeof AppDashboardCoursesSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/courses/$slug'
    | '/payment/$courseId'
    | '/dashboard/enrolled'
    | '/dashboard/home'
    | '/dashboard/resources'
    | '/courses/$slug/$week'
    | '/courses/$slug/introduction'
    | '/dashboard/courses/new'
    | '/payment/$courseId/$'
    | '/payment/$courseId/callback'
    | '/payment/$courseId/pay'
    | '/dashboard/courses'
    | '/dashboard/courses/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/courses/$slug'
    | '/payment/$courseId'
    | '/dashboard/enrolled'
    | '/dashboard/home'
    | '/dashboard/resources'
    | '/courses/$slug/$week'
    | '/courses/$slug/introduction'
    | '/dashboard/courses/new'
    | '/payment/$courseId/$'
    | '/payment/$courseId/callback'
    | '/payment/$courseId/pay'
    | '/dashboard/courses'
    | '/dashboard/courses/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/assessment'
    | '/_app/dashboard'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_app/courses/$slug'
    | '/_app/payment/$courseId'
    | '/_app/dashboard/enrolled'
    | '/_app/dashboard/home'
    | '/_app/dashboard/resources'
    | '/_app/courses/$slug/$week'
    | '/_app/courses/$slug/introduction'
    | '/_app/dashboard/courses/new'
    | '/_app/payment/$courseId/$'
    | '/_app/payment/$courseId/callback'
    | '/_app/payment/$courseId/pay'
    | '/_app/dashboard/courses/'
    | '/_app/dashboard/courses/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AssessmentRoute: typeof AssessmentRoute
}
export interface FileServerRoutesByFullPath {
  '/api/info': typeof ApiInfoServerRoute
}
export interface FileServerRoutesByTo {
  '/api/info': typeof ApiInfoServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/info': typeof ApiInfoServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/info'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/info'
  id: '__root__' | '/api/info'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiInfoServerRoute: typeof ApiInfoServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/resources': {
      id: '/_app/dashboard/resources'
      path: '/resources'
      fullPath: '/dashboard/resources'
      preLoaderRoute: typeof AppDashboardResourcesRouteImport
      parentRoute: typeof AppDashboardRouteRoute
    }
    '/_app/dashboard/home': {
      id: '/_app/dashboard/home'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof AppDashboardHomeRouteImport
      parentRoute: typeof AppDashboardRouteRoute
    }
    '/_app/dashboard/enrolled': {
      id: '/_app/dashboard/enrolled'
      path: '/enrolled'
      fullPath: '/dashboard/enrolled'
      preLoaderRoute: typeof AppDashboardEnrolledRouteImport
      parentRoute: typeof AppDashboardRouteRoute
    }
    '/_app/payment/$courseId': {
      id: '/_app/payment/$courseId'
      path: '/payment/$courseId'
      fullPath: '/payment/$courseId'
      preLoaderRoute: typeof AppPaymentCourseIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/courses/$slug': {
      id: '/_app/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof AppCoursesSlugRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/courses/': {
      id: '/_app/dashboard/courses/'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof AppDashboardCoursesIndexRouteImport
      parentRoute: typeof AppDashboardRouteRoute
    }
    '/_app/payment/$courseId/pay': {
      id: '/_app/payment/$courseId/pay'
      path: '/pay'
      fullPath: '/payment/$courseId/pay'
      preLoaderRoute: typeof AppPaymentCourseIdPayRouteImport
      parentRoute: typeof AppPaymentCourseIdRouteRoute
    }
    '/_app/payment/$courseId/callback': {
      id: '/_app/payment/$courseId/callback'
      path: '/callback'
      fullPath: '/payment/$courseId/callback'
      preLoaderRoute: typeof AppPaymentCourseIdCallbackRouteImport
      parentRoute: typeof AppPaymentCourseIdRouteRoute
    }
    '/_app/payment/$courseId/$': {
      id: '/_app/payment/$courseId/$'
      path: '/$'
      fullPath: '/payment/$courseId/$'
      preLoaderRoute: typeof AppPaymentCourseIdSplatRouteImport
      parentRoute: typeof AppPaymentCourseIdRouteRoute
    }
    '/_app/dashboard/courses/new': {
      id: '/_app/dashboard/courses/new'
      path: '/courses/new'
      fullPath: '/dashboard/courses/new'
      preLoaderRoute: typeof AppDashboardCoursesNewRouteImport
      parentRoute: typeof AppDashboardRouteRoute
    }
    '/_app/courses/$slug/introduction': {
      id: '/_app/courses/$slug/introduction'
      path: '/introduction'
      fullPath: '/courses/$slug/introduction'
      preLoaderRoute: typeof AppCoursesSlugIntroductionRouteImport
      parentRoute: typeof AppCoursesSlugRouteRoute
    }
    '/_app/courses/$slug/$week': {
      id: '/_app/courses/$slug/$week'
      path: '/$week'
      fullPath: '/courses/$slug/$week'
      preLoaderRoute: typeof AppCoursesSlugWeekRouteImport
      parentRoute: typeof AppCoursesSlugRouteRoute
    }
    '/_app/dashboard/courses/$slug/edit': {
      id: '/_app/dashboard/courses/$slug/edit'
      path: '/courses/$slug/edit'
      fullPath: '/dashboard/courses/$slug/edit'
      preLoaderRoute: typeof AppDashboardCoursesSlugEditRouteImport
      parentRoute: typeof AppDashboardRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/info': {
      id: '/api/info'
      path: '/api/info'
      fullPath: '/api/info'
      preLoaderRoute: typeof ApiInfoServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AppDashboardRouteRouteChildren {
  AppDashboardEnrolledRoute: typeof AppDashboardEnrolledRoute
  AppDashboardHomeRoute: typeof AppDashboardHomeRoute
  AppDashboardResourcesRoute: typeof AppDashboardResourcesRoute
  AppDashboardCoursesNewRoute: typeof AppDashboardCoursesNewRoute
  AppDashboardCoursesIndexRoute: typeof AppDashboardCoursesIndexRoute
  AppDashboardCoursesSlugEditRoute: typeof AppDashboardCoursesSlugEditRoute
}

const AppDashboardRouteRouteChildren: AppDashboardRouteRouteChildren = {
  AppDashboardEnrolledRoute: AppDashboardEnrolledRoute,
  AppDashboardHomeRoute: AppDashboardHomeRoute,
  AppDashboardResourcesRoute: AppDashboardResourcesRoute,
  AppDashboardCoursesNewRoute: AppDashboardCoursesNewRoute,
  AppDashboardCoursesIndexRoute: AppDashboardCoursesIndexRoute,
  AppDashboardCoursesSlugEditRoute: AppDashboardCoursesSlugEditRoute,
}

const AppDashboardRouteRouteWithChildren =
  AppDashboardRouteRoute._addFileChildren(AppDashboardRouteRouteChildren)

interface AppCoursesSlugRouteRouteChildren {
  AppCoursesSlugWeekRoute: typeof AppCoursesSlugWeekRoute
  AppCoursesSlugIntroductionRoute: typeof AppCoursesSlugIntroductionRoute
}

const AppCoursesSlugRouteRouteChildren: AppCoursesSlugRouteRouteChildren = {
  AppCoursesSlugWeekRoute: AppCoursesSlugWeekRoute,
  AppCoursesSlugIntroductionRoute: AppCoursesSlugIntroductionRoute,
}

const AppCoursesSlugRouteRouteWithChildren =
  AppCoursesSlugRouteRoute._addFileChildren(AppCoursesSlugRouteRouteChildren)

interface AppPaymentCourseIdRouteRouteChildren {
  AppPaymentCourseIdSplatRoute: typeof AppPaymentCourseIdSplatRoute
  AppPaymentCourseIdCallbackRoute: typeof AppPaymentCourseIdCallbackRoute
  AppPaymentCourseIdPayRoute: typeof AppPaymentCourseIdPayRoute
}

const AppPaymentCourseIdRouteRouteChildren: AppPaymentCourseIdRouteRouteChildren =
  {
    AppPaymentCourseIdSplatRoute: AppPaymentCourseIdSplatRoute,
    AppPaymentCourseIdCallbackRoute: AppPaymentCourseIdCallbackRoute,
    AppPaymentCourseIdPayRoute: AppPaymentCourseIdPayRoute,
  }

const AppPaymentCourseIdRouteRouteWithChildren =
  AppPaymentCourseIdRouteRoute._addFileChildren(
    AppPaymentCourseIdRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppDashboardRouteRoute: typeof AppDashboardRouteRouteWithChildren
  AppCoursesSlugRouteRoute: typeof AppCoursesSlugRouteRouteWithChildren
  AppPaymentCourseIdRouteRoute: typeof AppPaymentCourseIdRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRouteRoute: AppDashboardRouteRouteWithChildren,
  AppCoursesSlugRouteRoute: AppCoursesSlugRouteRouteWithChildren,
  AppPaymentCourseIdRouteRoute: AppPaymentCourseIdRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AssessmentRoute: AssessmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiInfoServerRoute: ApiInfoServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
