/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteRouteImport } from './routes/auth/signup/route'
import { Route as AuthLoginRouteRouteImport } from './routes/auth/login/route'
import { Route as AuthSignupStudentsRouteImport } from './routes/auth/signup/students'
import { Route as AuthSignupInstructorRouteImport } from './routes/auth/signup/instructor'
import { Route as AuthLoginStudentsRouteImport } from './routes/auth/login/students'
import { Route as AuthLoginInstructorRouteImport } from './routes/auth/login/instructor'
import { Route as AppDashboardCreateCourseRouteImport } from './routes/_app/dashboard/create-course'
import { Route as AppDashboardCoursesRouteImport } from './routes/_app/dashboard/courses'
import { Route as AppCoursesSlugIntroductionRouteImport } from './routes/_app/courses/$slug/introduction'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRouteRoute = AuthSignupRouteRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRouteRoute = AuthLoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupStudentsRoute = AuthSignupStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthSignupRouteRoute,
} as any)
const AuthSignupInstructorRoute = AuthSignupInstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => AuthSignupRouteRoute,
} as any)
const AuthLoginStudentsRoute = AuthLoginStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthLoginRouteRoute,
} as any)
const AuthLoginInstructorRoute = AuthLoginInstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => AuthLoginRouteRoute,
} as any)
const AppDashboardCreateCourseRoute =
  AppDashboardCreateCourseRouteImport.update({
    id: '/dashboard/create-course',
    path: '/dashboard/create-course',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardCoursesRoute = AppDashboardCoursesRouteImport.update({
  id: '/dashboard/courses',
  path: '/dashboard/courses',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoursesSlugIntroductionRoute =
  AppCoursesSlugIntroductionRouteImport.update({
    id: '/courses/$slug/introduction',
    path: '/courses/$slug/introduction',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRouteRouteWithChildren
  '/auth/signup': typeof AuthSignupRouteRouteWithChildren
  '/dashboard/courses': typeof AppDashboardCoursesRoute
  '/dashboard/create-course': typeof AppDashboardCreateCourseRoute
  '/auth/login/instructor': typeof AuthLoginInstructorRoute
  '/auth/login/students': typeof AuthLoginStudentsRoute
  '/auth/signup/instructor': typeof AuthSignupInstructorRoute
  '/auth/signup/students': typeof AuthSignupStudentsRoute
  '/courses/$slug/introduction': typeof AppCoursesSlugIntroductionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRouteRouteWithChildren
  '/auth/signup': typeof AuthSignupRouteRouteWithChildren
  '/dashboard/courses': typeof AppDashboardCoursesRoute
  '/dashboard/create-course': typeof AppDashboardCreateCourseRoute
  '/auth/login/instructor': typeof AuthLoginInstructorRoute
  '/auth/login/students': typeof AuthLoginStudentsRoute
  '/auth/signup/instructor': typeof AuthSignupInstructorRoute
  '/auth/signup/students': typeof AuthSignupStudentsRoute
  '/courses/$slug/introduction': typeof AppCoursesSlugIntroductionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRouteRouteWithChildren
  '/auth/signup': typeof AuthSignupRouteRouteWithChildren
  '/_app/dashboard/courses': typeof AppDashboardCoursesRoute
  '/_app/dashboard/create-course': typeof AppDashboardCreateCourseRoute
  '/auth/login/instructor': typeof AuthLoginInstructorRoute
  '/auth/login/students': typeof AuthLoginStudentsRoute
  '/auth/signup/instructor': typeof AuthSignupInstructorRoute
  '/auth/signup/students': typeof AuthSignupStudentsRoute
  '/_app/courses/$slug/introduction': typeof AppCoursesSlugIntroductionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/courses'
    | '/dashboard/create-course'
    | '/auth/login/instructor'
    | '/auth/login/students'
    | '/auth/signup/instructor'
    | '/auth/signup/students'
    | '/courses/$slug/introduction'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/courses'
    | '/dashboard/create-course'
    | '/auth/login/instructor'
    | '/auth/login/students'
    | '/auth/signup/instructor'
    | '/auth/signup/students'
    | '/courses/$slug/introduction'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/auth/login'
    | '/auth/signup'
    | '/_app/dashboard/courses'
    | '/_app/dashboard/create-course'
    | '/auth/login/instructor'
    | '/auth/login/students'
    | '/auth/signup/instructor'
    | '/auth/signup/students'
    | '/_app/courses/$slug/introduction'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signup/students': {
      id: '/auth/signup/students'
      path: '/students'
      fullPath: '/auth/signup/students'
      preLoaderRoute: typeof AuthSignupStudentsRouteImport
      parentRoute: typeof AuthSignupRouteRoute
    }
    '/auth/signup/instructor': {
      id: '/auth/signup/instructor'
      path: '/instructor'
      fullPath: '/auth/signup/instructor'
      preLoaderRoute: typeof AuthSignupInstructorRouteImport
      parentRoute: typeof AuthSignupRouteRoute
    }
    '/auth/login/students': {
      id: '/auth/login/students'
      path: '/students'
      fullPath: '/auth/login/students'
      preLoaderRoute: typeof AuthLoginStudentsRouteImport
      parentRoute: typeof AuthLoginRouteRoute
    }
    '/auth/login/instructor': {
      id: '/auth/login/instructor'
      path: '/instructor'
      fullPath: '/auth/login/instructor'
      preLoaderRoute: typeof AuthLoginInstructorRouteImport
      parentRoute: typeof AuthLoginRouteRoute
    }
    '/_app/dashboard/create-course': {
      id: '/_app/dashboard/create-course'
      path: '/dashboard/create-course'
      fullPath: '/dashboard/create-course'
      preLoaderRoute: typeof AppDashboardCreateCourseRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/courses': {
      id: '/_app/dashboard/courses'
      path: '/dashboard/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof AppDashboardCoursesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/courses/$slug/introduction': {
      id: '/_app/courses/$slug/introduction'
      path: '/courses/$slug/introduction'
      fullPath: '/courses/$slug/introduction'
      preLoaderRoute: typeof AppCoursesSlugIntroductionRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardCoursesRoute: typeof AppDashboardCoursesRoute
  AppDashboardCreateCourseRoute: typeof AppDashboardCreateCourseRoute
  AppCoursesSlugIntroductionRoute: typeof AppCoursesSlugIntroductionRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardCoursesRoute: AppDashboardCoursesRoute,
  AppDashboardCreateCourseRoute: AppDashboardCreateCourseRoute,
  AppCoursesSlugIntroductionRoute: AppCoursesSlugIntroductionRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthLoginRouteRouteChildren {
  AuthLoginInstructorRoute: typeof AuthLoginInstructorRoute
  AuthLoginStudentsRoute: typeof AuthLoginStudentsRoute
}

const AuthLoginRouteRouteChildren: AuthLoginRouteRouteChildren = {
  AuthLoginInstructorRoute: AuthLoginInstructorRoute,
  AuthLoginStudentsRoute: AuthLoginStudentsRoute,
}

const AuthLoginRouteRouteWithChildren = AuthLoginRouteRoute._addFileChildren(
  AuthLoginRouteRouteChildren,
)

interface AuthSignupRouteRouteChildren {
  AuthSignupInstructorRoute: typeof AuthSignupInstructorRoute
  AuthSignupStudentsRoute: typeof AuthSignupStudentsRoute
}

const AuthSignupRouteRouteChildren: AuthSignupRouteRouteChildren = {
  AuthSignupInstructorRoute: AuthSignupInstructorRoute,
  AuthSignupStudentsRoute: AuthSignupStudentsRoute,
}

const AuthSignupRouteRouteWithChildren = AuthSignupRouteRoute._addFileChildren(
  AuthSignupRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRouteRoute: typeof AuthLoginRouteRouteWithChildren
  AuthSignupRouteRoute: typeof AuthSignupRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRouteRoute: AuthLoginRouteRouteWithChildren,
  AuthSignupRouteRoute: AuthSignupRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
